config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: :logout
  get 'register', to: 'users#new', as: :register


  resources :posts, except: [:destroy] do
    member do
      post :vote
    end
    
    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end

  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:show, :create, :edit, :update]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable
  
  belongs_to :creator, foreign_key: :user_id, class_name: 'User'
  belongs_to :post, foreign_key: :post_id

  validates :body, presence: true


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :ensure_logged_in

  def create
    @post = Post.find_by(slug: params[:post_id])
    @comment = @post.comments.build(params.require(:comment).permit(:body))
    @comment.creator = current_user

    if @comment.save
      flash[:notice] = "Your comment was added"
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def vote
    @comment = Comment.find(params[:id])

    @vote = Vote.new(vote: params[:vote], voteable: @comment, creator: current_user)

    if @vote.save
      respond_to do |format|
        format.html do
          flash[:notice] = "Your vote was counted"
          redirect_to :back
        end
        format.js
      end
    else
      respond_to do |format|
        flash[:error] = "You may only vote on that once"
        format.html { redirect_to :back }
        format.js
      end
    end
  end
end

app/views/comments/_comment.html.erb
<% show_post ||= false %>

<div class='row'>
  <div class="span0 well text-center">
    <% if logged_in? %>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: 'post', remote: true do %>
        <i class='icon-arrow-up'></i>
      <% end %>
      <br/>
    <% end %>
     <span id='comment_<%= comment.id %>_votes'><%= "#{comment.total_votes}" %></span> <%= "vote#{comment.total_votes == 1 ? '' : 's'}" %>
    <br/>
    <% if logged_in? %>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: 'post', remote: true do %>
        <i class='icon-arrow-down'></i>
      <% end %>
    <% end%>
  </div>
  <div class='span8 well'>
    <span class="quiet">posted by</span> <%= link_to comment.creator.username, user_path(comment.creator) %>
    <% if show_post %>
      <span>on  <%= link_to "#{comment.post.title}", post_path(comment.post) %></span>
    <% end %>
    <small><%= format_date comment.created_at %></small>
      <p><%= comment.body %></p>
  </div>
</div>

app/views/comments/vote.js.erb
<% if (@vote.valid?) %>
  $('#comment_<%= @comment.id %>_votes').html(<%= "#{@comment.total_votes}" %>)
<% else %>
  $('div.alert').remove();
  $('div.row > div.span12').prepend('<%= ajax_flash %>')
<% end%>