config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: :logout
  get 'register', to: 'users#new', as: :register


  resources :posts, except: [:destroy] do
    member do
      post :vote
    end
    
    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end

  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:show, :create, :edit, :update]
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable
  include Sluggable
  
  belongs_to :creator, foreign_key: :user_id, class_name: 'User'
  has_many :comments, foreign_key: :post_id
  has_many :post_categories
  has_many :categories, through: :post_categories

  before_save -> { generate_slug('title') }

  validates :title, presence: true, length: {minimum: 5}
  validates :url, presence: true, uniqueness: true
  validates :description, presence: true


  

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :set_categories, only: [:show, :edit, :new, :update]
  before_action :ensure_logged_in, only: [:new, :create, :edit, :update, :vote]
  before_action :ensure_edit_permissions, only: [:edit, :update]

  def index
    @posts = Post.all.sort_by{|x| x.total_votes}.reverse
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user

    if @post.save
      flash[:notice] = "Your post was created"
      redirect_to posts_path
    else
      render 'posts/new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Your post was edited"
      redirect_to posts_path(@post)
    else
      render 'posts/edit'
    end
  end

  def vote
    @vote = Vote.new(creator: current_user, voteable: @post, vote: params[:vote])
  
    if @vote.save
      respond_to do |format|
        format.html do
          flash[:notice] = "Your vote was counted"
          redirect_to :back
        end
        format.js
      end
    else
      respond_to do |format|
        flash[:error] = "You may only vote on that once"
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end

  def set_post
    @post = Post.find_by(slug: params[:id])    
  end

  def set_categories
    @categories = Category.all
  end

  def allowed_to_edit
    admin? || current_user == @post.creator
  end

  def ensure_edit_permissions
    access_denied unless allowed_to_edit
  end
end

app/views/posts/_form.html.erb
<%= render 'shared/form_error', form: @post %>
<div class="row">
  <div class='span8 well'>
    <%= form_for @post do |f| %>
      <div class='control-group'>
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>
      <div class='control-group'>
        <%= f.label :url %>
        <%= f.text_field :url %>
      </div>
      <div class='control-group'>
        <%= f.label :description %>
        <%= f.text_area :description, rows: 5 %>
      </div>
      <br>
      <div class='control-group'>
        <%=  collection_check_boxes(:post, :category_ids, @categories, :id, :name) do |b|
              b.label(class: "checkbox inline") { b.check_box + b.text} 
              end %>
      </div>
      <%= submit_tag btn_txt, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="row">
  <div class="span0 well text-center">
    <% if logged_in?%>
      <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
        <i class='icon-arrow-up'></i>
      <% end %>
    <br/>
    <% end %>
    <span id='post_<%= post.id %>_votes'><%= "#{post.total_votes}" %></span> vote<%= "#{post.total_votes == 1 ? '' : 's'}" %>
    <br/>
    <% if logged_in? %>
      <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %>
        <i class='icon-arrow-down'></i>
      <% end %>
    <% end %>
  </div>
  <div class="span8 well">
    <%= render post.categories %>
    <h4><%= link_to post.title, post_path(post) %></h4>
    <p><%= link_to post.url, format_url(post.url) %></p>
    <p><%= post.description %></p>
    <p>
      <span class="quiet">posted by</span> <%= link_to post.creator.username, user_path(post.creator) %>
      <small><%= format_date post.created_at %></small>
    </p>
    <small>
      <span>
        <%= link_to("#{post.comments.size} comments", post_path(post)) %>
      </span>
    </small>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: 'Edit your post' %>

<%= render 'form', btn_txt: 'Edit post' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: "All Posts" %>

<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: 'Create a new post' %>

<%= render 'form', btn_txt: 'Create post' %>

app/views/posts/show.html.erb
<% if admin? || current_user == @post.creator%>
  <p class='pull-right'>
    [<%= link_to 'edit this post', edit_post_path(@post) %>]
  </p>
<% end %>

<p>
  <%= render @post.categories %>
</p>

<%= render 'shared/content_title', title: @post.title %>

<h4><%= link_to @post.url, format_url(@post.url) %></h4>
<p>
  <%= @post.description %>
</p>

<% if logged_in? %>
  <%= form_for [@post, @comment] do |f| %>
    <div class='control-group'>
      <%= render 'shared/form_error', form: @comment %>
      <%= f.label :body, 'Leave a Comment' %>
      <%= f.text_area :body, rows: 3, class: 'span4' %><br>
      <%= f.submit class: 'btn btn-primary block' %>
    </div>
  <% end %>
<% end %>


<h4>Comments:</h4>
<% @post.reload.comments.sort_by{|x| x.total_votes}.reverse.each do |comment| %>
 <%= render 'comments/comment', comment: comment %>
<% end %>

app/views/posts/vote.js.erb
<% if (@vote.valid?) %>
  $('#post_<%= @post.id %>_votes').html(<%= "#{@post.total_votes}" %>)
<% else %>
  $('div.alert').remove();
  $('div.row > div.span12').prepend('<%= ajax_flash %>')
<% end%>