config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: :logout
  get 'register', to: 'users#new', as: :register


  resources :posts, except: [:destroy] do
    member do
      post :vote
    end
    
    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end

  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:show, :create, :edit, :update]
end

app/models/category.rb
class Category < ActiveRecord::Base
  include Sluggable

  has_many :post_categories
  has_many :posts, through: :post_categories

  before_save -> { generate_slug('name') }

  validates :name, presence: true

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :ensure_logged_in, except: [:index, :show]
  before_action :ensure_admin, only: [:new]
  
  def index
  end

  def show
    @category = Category.find_by(slug: params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = 'Your category was saved'
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    
  end

  def update
    
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end


end

app/views/categories/_category.html.erb
 <span class="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/_form.html.erb
<%= render 'shared/form_error', form: @category %>

<div class='well'>
  <%= form_for @category do |f| %>
    <div class='control-group'>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <br>
    <%= submit_tag btn_txt, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: 'Create a new category' %>

<%= render 'form', btn_txt: 'Create Category' %>

app/views/categories/show.html.erb
<% all_posts = link_to('All Posts', posts_path) %>

<%= render 'shared/content_title', title: "#{all_posts} &raquo; #{@category.name}".html_safe %>

<% @category.posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>